-- ============================================================================
-- Q9 — "Diamond Hands" vs. Scalpers (Duration Psychology)
-- ----------------------------------------------------------------------------
-- Dune query ID : (save with `dune query create`)
-- Purpose       : Analyzes trader psychology by categorizing trades based on
--                 hold duration (openedAt to closedAt). It compares the win
--                 rate, average PnL, and behavior between quick scalps, intra-day
--                 trades, and multi-day swings. It also exposes the classic
--                 retail trap: do traders hold losers longer than winners?
-- Source        : dojifunded_arbitrum.dojitradenft_call_minttrade (decoded CALL).
--
-- Decimals      : realizedPnl = 1e6 (USD). openedAt/closedAt = unix seconds.
-- ============================================================================
WITH trades AS (
    SELECT
        CAST(json_extract_scalar(data, '$.openedAt') AS BIGINT)   AS opened_at,
        CAST(json_extract_scalar(data, '$.closedAt') AS BIGINT)   AS closed_at,
        CAST(json_extract_scalar(data, '$.realizedPnl') AS DOUBLE) AS pnl_raw
    FROM dojifunded_arbitrum.dojitradenft_call_minttrade
    WHERE call_success = true
      -- Filter out corrupted or zero-duration timestamps
      AND CAST(json_extract_scalar(data, '$.closedAt') AS BIGINT) > CAST(json_extract_scalar(data, '$.openedAt') AS BIGINT)
      AND call_block_time >= TIMESTAMP '2026-05-01'
      AND "to" != 0xf60ffefeea868d0a77d5b055df07c18022c7f7bc       -- exclude internal testing
),
durations AS (
    SELECT
        pnl_raw / 1e6 AS realized_pnl_usd,
        (closed_at - opened_at) AS duration_seconds,
        CASE
            WHEN (closed_at - opened_at) < 300 THEN '1. Scalp (< 5m)'
            WHEN (closed_at - opened_at) < 14400 THEN '2. Day (5m - 4h)'
            WHEN (closed_at - opened_at) < 86400 THEN '3. Extended Day (4h - 24h)'
            ELSE '4. Swing (> 24h)'
        END AS trading_style,
        CASE WHEN pnl_raw > 0 THEN 'Win' ELSE 'Loss' END AS trade_result
    FROM trades
)
SELECT
    trading_style,
    COUNT(*) AS total_trades,

    -- Win Rate %
    ROUND(100.0 * COUNT(CASE WHEN trade_result = 'Win' THEN 1 END) / COUNT(*), 1) AS win_rate_pct,

    -- Average PnL per trade in this bucket
    ROUND(AVG(realized_pnl_usd), 2) AS avg_pnl_usd,

    -- Total PnL generated by this style
    ROUND(SUM(realized_pnl_usd), 2) AS total_pnl_usd,

    -- Hold time analysis (Winner vs Loser)
    ROUND(AVG(CASE WHEN trade_result = 'Win' THEN duration_seconds END) / 60.0, 1) AS avg_winner_hold_minutes,
    ROUND(AVG(CASE WHEN trade_result = 'Loss' THEN duration_seconds END) / 60.0, 1) AS avg_loser_hold_minutes,

    -- The "Hope" Ratio: > 1 means traders hold losers longer than winners.
    ROUND(
        AVG(CASE WHEN trade_result = 'Loss' THEN duration_seconds END) /
        NULLIF(AVG(CASE WHEN trade_result = 'Win' THEN duration_seconds END), 0),
        2
    ) AS loser_to_winner_hold_ratio

FROM durations
GROUP BY trading_style
ORDER BY trading_style ASC;
